if (!ß.BACKGROUND_OVERLAY_COLOR) ß.BACKGROUND_OVERLAY_COLOR = "#000000";
if (!ß.BACKGROUND_OVERLAY_ALPHA) ß.BACKGROUND_OVERLAY_ALPHA =  "0.5";
if (!ß.BACKGROUND_WEBKIT_FILTER) ß.BACKGROUND_WEBKIT_FILTER =  'blur(0px)';