if (!ß.APPINSPECTOR_STARTUPTIME_WAIT) ß.APPINSPECTOR_STARTUPTIME_WAIT = 120000; //ms
if (!ß.APPINSPECTOR_CPUTHRESHOLD) ß.APPINSPECTOR_CPUTHRESHOLD = 25; //%
if (!ß.APPINSPECTOR_MEMTHRESHOLD) ß.APPINSPECTOR_MEMTHRESHOLD = 80; //MB
if (!ß.APPINSPECTOR_MONITORFREQ) ß.APPINSPECTOR_MONITORFREQ = 30000; //ms
if (!ß.APPINSPECTOR_MAX_NUM_MEMDUMP) ß.APPINSPECTOR_MAX_NUM_MEMDUMP = 20; 
if (!ß.APPINSPECTOR_MAX_NUM_CPUDUMP) ß.APPINSPECTOR_MAX_NUM_CPUDUMP = 40;
if (!ß.APPINSPECTOR_DIFFBETWEEN_MEMDUMPS) ß.APPINSPECTOR_DIFFBETWEEN_MEMDUMPS = 20; //%
if (!ß.APPINSPECTOR_CPUPROFILE_DURATION) ß.APPINSPECTOR_CPUPROFILE_DURATION = 5000; //ms

//If there is more than xPercent difference between 2 memory usage than we take new one
if (!ß.APPINSPECTOR_SAVEDIR)  ß.APPINSPECTOR_SAVEDIR = ß.VAR + "/profiles";

ß.fs.removeSync(ß.APPINSPECTOR_SAVEDIR);
ß.fs.ensureDirSync(ß.APPINSPECTOR_SAVEDIR);

ß.appinspector_num_cpudumps = 0;
ß.appinspector_num_memdumps = 0;


